Ignore metaparams for default translation as well
The `before` metaparam caused following error on a conservative run:

```
super_vagrant@faalserver:/vagrant# puppet yamlresource package 'htop' '{"provider": "apt", "ensure": "latest", "before": [{type: "Package", title: "resolvconf",
            tags: {hash: {"package": true, "resolvconf": true}}, parameters: {}}], "configfiles": "keep",
        "reinstall_on_refresh": "false", "loglevel": "notice"}'
Error: Parameter before failed on Package[htop]: Puppet::Resource.new does not take a hash as the first argument. Did you mean ("Package", "resolvconf") ?
Error: Try 'puppet help yamlresource find_or_save' for usage
```